import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Conditions générales d’utilisation", description: "Les conditions d’accès et d’utilisation de PelotonFR, calendrier indépendant du cyclisme amateur.", alternates: { canonical: "/cgu" } };
export default function Terms() {
  return <article className="mx-auto max-w-2xl space-y-8 px-4 py-10 text-sm leading-relaxed">
    <header><h1 className="font-heading text-4xl font-bold">Conditions générales d’utilisation</h1><p className="mt-3 text-muted-foreground">Version du 17 septembre 2026 · PelotonFR, édité par Théo Guyard.</p></header>
    <section><h2 className="mb-2 text-xl font-semibold">Le service</h2><p>PelotonFR aide à trouver des courses cyclistes et à préparer une saison. Le calendrier public est accessible gratuitement. Les fonctions de compte permettent notamment de conserver des courses et des préférences. Aucun abonnement payant n’est proposé dans cette version.</p></section>
    <section><h2 className="mb-2 text-xl font-semibold">Compte et accès</h2><p>Utilise une adresse et des comptes auxquels tu as légitimement accès. Garde tes liens de connexion et codes de suivi privés. Un rattachement à un profil fédéral est déclaratif et ne prouve pas ton identité. Les accès partagés d’un club demandent une vérification opérateur. Les mineurs utilisent le service avec l’accord de leur représentant légal.</p></section>
    <section><h2 className="mb-2 text-xl font-semibold">Informations sportives</h2><p>Les calendriers et résultats proviennent de sources identifiées qui peuvent changer. Vérifie les horaires, catégories, inscriptions, annulations et consignes auprès de l’organisateur avant de te déplacer. Un ajout à « Ma saison » n’est pas une inscription à une épreuve. Les estimations, tracés et images ne garantissent ni l’état de la route ni la sécurité du parcours ; respecte les règles de circulation et les instructions de l’organisateur.</p></section>
    <section><h2 className="mb-2 text-xl font-semibold">Contributions et comportement</h2><p>Ne transmets que les informations que tu peux légitimement partager. N’usurpe pas l’identité d’un coureur ou d’un club ; ne publie pas de contenu illicite, trompeur ou portant atteinte aux autres. Les propositions de circuits sont soumises à revue et ne remplacent pas immédiatement la fiche publique. Les tentatives de contournement des accès, le spam et les requêtes destinées à perturber le service sont interdits. Un accès peut être limité ou suspendu pour protéger les utilisateurs ; une contestation peut être adressée via Contact.</p></section>
    <section><h2 className="mb-2 text-xl font-semibold">Sources et droits</h2><p>Les noms, marques, données et images de tiers restent soumis à leurs droits et licences. Consulter une page ne transfère aucun droit de réutilisation. Cite les sources et vérifie les conditions du fournisseur avant une réutilisation. Les usages collectifs Strava restent désactivés tant que leurs conditions n’ont pas été validées.</p></section>
    <section><h2 className="mb-2 text-xl font-semibold">Disponibilité et responsabilité</h2><p>Le service peut être interrompu pour maintenance ou en cas de panne. Les erreurs signalées sont examinées, sans garantie d’exhaustivité ou de disponibilité permanente. Ces conditions ne limitent pas les droits impératifs des utilisateurs ni la responsabilité qui ne peut légalement être exclue.</p></section>
    <section><h2 className="mb-2 text-xl font-semibold">Données, demandes et évolution</h2><p>La <Link href="/confidentialite" className="underline">politique de confidentialité</Link> décrit les traitements et tes droits. Pour demander la fermeture d’un compte, signaler une erreur ou contester une décision, utilise <Link href="/contact" className="underline">Contact</Link> et conserve le code de suivi. Les conditions mises à jour seront datées sur cette page. Le droit français s’applique, sous réserve des protections impératives applicables à l’utilisateur ; aucun tribunal exclusif n’est imposé ici.</p></section>
  </article>;
}
